version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pongfight-net
    env_file:
      - ./backend/.env
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra
    ports:
      - 8080:8080
    networks:
      - pongfight-net
    depends_on:
      - postgres
    restart: always

  next:
    container_name: frontend
    build: ./frontend
    ports:
      - 3001:3000
    restart: always

  nest:
    container_name: nest
    build: ./backend/
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - pongfight-net
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/public:/app/public
    restart: always

networks:
  pongfight-net:
    name: pongfight-net
    driver: bridge

volumes:
  db_data:
    name: db_data
