version: "3.8"

services:
  #frontend:
  #  build:
  #    context: frontend
  #    target: development
  #    depends_on:
  #      - 

  #backend:
  #  build:
  #    context: backend
  #    target: development
  #    depends_on:
  #      - db

  db:
    container_name: db
    image: postgres:15.3-alpine
    env_file:
      .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra
    ports:
      - 8080:8080
    networks:
      - app-net
    depends_on:
      - db
    restart: always
#
#  nginx:
#    container_name: nginx
#    build: ./backend/
#    volumes:
#      - /frontend:/var/www/html
#    depends_on:
#      - postgresql
#    ports:
#      - 8001:8001
#    restart: always

networks:
  app-net:
    name: app-net
