version: "3.8"

services:
  #frontend:
  #  build:
  #    context: frontend
  #    target: development
  #    depends_on:
  #      - 

  backend:
    container_name: transcendence_backend
    build: ./backend
    depends_on:
      - postgres
      - adminer
      - nest

  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
    # - ./data:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net
    env_file:
      - ./backend/.env
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra
    ports:
      - 8080:8080
    networks:
      - app-net
    depends_on:
      - postgres
    restart: always

  nest:
      container_name: nest
      build: ./backend/
      depends_on:
        - postgres
      ports:
        - 3000:3000
      networks:
        - app-net
      restart: always

#  nginx:
#    container_name: nginx
#    build: ./frontend/
#    volumes:
#      - /frontend:/var/www/html
#    depends_on:
#      - backend
#    ports:
#      - 8001:8001
#    restart: always

networks:
  app-net:
    name: app-net
    driver: bridge

volumes:
  db_data: