version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net
    env_file:
      - ./backend/.env
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra
    ports:
      - 8080:8080
    networks:
      - app-net
    depends_on:
      - postgres
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend/common:/app/common
      - ./frontend/app:/app/app
      - ./frontend/public:/app/public
      - ./frontend/contexts:/app/contexts
    restart: always

  nest:
    container_name: nest
    build: ./backend/
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - app-net
    env_file:
      - ./backend/.env

    #x-develop:
    #  watch:
    #    - action: sync
    #      path: ./backend
    #      target: /app
    #      ignore:
    #        - node_modules/

    # TODO
    # Remove the first 2 volumes in prod
    volumes:
      - ./backend/src:/app/src
      - ./backend/types:/app/types
      - ./backend/public:/app/public
    restart: always

networks:
  app-net:
    name: app-net
    driver: bridge

volumes:
  db_data:
