import './globals.css'
import { Press_Start_2P } from 'next/font/google'

const pressStart = Press_Start_2P({ weight: "400", subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pressStart.className}>
		<div className="h-screen bg-gradient-to-tr from-black via-[#221922] to-black overflow-y-hidden">
		{children}
		</div>
	  </body>
    </html>
  )
}
